schema_version = "1.0.0"
id = "meshy_autoglb"
version = "4.5.8"
name = "Meshy-AutoGLB"
tagline = "GLB模型管理工具"
maintainer = "xiangyu"
type = "add-on"
blender_version_min = "4.0.0"
license = ["SPDX:GPL-3.0-or-later"]
