schema_version = "1.0.0"
id = "meshy_automodel"
version = "4.6.10"
name = "Meshy-AutoModel"
tagline = "GLB/USDZ模型管理工具"
maintainer = "xiangyu"
type = "add-on"
blender_version_min = "4.0.0"
license = ["SPDX:GPL-3.0-or-later"]
